woowacourse-teams/2025-feed-zupzup

.github/workflows/discord-notification.yml
#9 
깃헙 웹 훅 세팅했습니다
backend, frontend 라벨 별 다른 채널에 보내도록 workflow 작성 했습니다
=> [BE/FE] 웹 훅 세팅

backend/src/main/java/feedzupzup/backend/feedback/domain/Feedback.java, backend/src/main/java/feedzupzup/backend/feedback/domain/ProcessStatus.java, backend/src/main/java/feedzupzup/backend/global/BaseTimeEntity.java, backend/src/main/java/feedzupzup/backend/global/JpaAuditingConfig.java, backend/src/main/java/feedzupzup/backend/place/Place.java
=> [BE] feat: 엔티티 세팅

backend/src/main/java/feedzupzup/backend/global/config/JpaAuditingConfig.java, backend/src/main/java/feedzupzup/backend/global/response/ErrorCode.java, backend/src/main/java/feedzupzup/backend/global/response/ErrorResponse.java, backend/src/main/java/feedzupzup/backend/global/response/SuccessResponse.java
#19 
- successResponse 정의
- errorResponse, errorcode 정의
=> [BE] feat: Api 응답 형식 세팅

frontend/src/components/Button/Button.tsx, frontend/src/components/commons/Button/Button.tsx, frontend/src/components/commons/Button/Button.types.ts, frontend/src/components/commons/Input/Input.tsx, frontend/src/components/commons/Input/Input.types.ts, frontend/src/components/commons/TextArea/TextArea.tsx, frontend/src/components/commons/TextArea/TextArea.types.ts
=> feat: 공통 컴포넌트 구현

frontend/babel.config.js, frontend/package-lock.json, frontend/package.json, frontend/src/components/commons/Button/Button.types.ts, frontend/src/components/commons/Input/Input.types.ts, frontend/src/components/commons/TextArea/TextArea.types.ts, frontend/tsconfig.json
close #39 
emotion react 사용에 필요한 설정을 했습니다.
=> [FE] chore: emotion 설정

.github/workflows/auto-close-issue.yml
=> [BE] chore: 이슈 자동 닫기 스크립트 작성

frontend/package-lock.json, frontend/package.json, frontend/src/index.tsx, frontend/src/router.tsx
=> [FE] chore: Router 설정 

frontend/src/domains/admin/home/AdminHome.tsx, frontend/src/domains/components/FeedbackBoxBackGround/FeedbackBoxBackGround.styles.ts, frontend/src/domains/components/FeedbackBoxList/FeedbackBoxList.styles.ts, frontend/src/domains/user/home/UserHome.tsx, frontend/src/router.tsx
close #110 
- 관리자 홈 화면 제작
- 사용자 홈 화면 제작
- 피드백 박스 배경 색상 흰색으로 변경
- 피드백 박스 리스트 마진 설정
=> [FE] feat: 홈화면 제작

frontend/src/sum.test.ts
=> [FE] fix: 테스트 오류 개선

.github/workflows/ci-cd.yml, .github/workflows/test.yml
#128 
ci-cd 시 서브 모듈의 최신 커밋을 바라보도록 명령어를 추가합니다~~
=> [BE] chore: ci-cd 시 서브모듈 최신화 step 추가

.github/workflows/ci-cd.yml, backend/src/main/java/feedzupzup/backend/global/config/CorsConfig.java
#146 
CORS 설정 추가 - localhost:3000 허용
=> [BE] cors 설정 추가

.github/workflows/ci-cd-prod.yml, .github/workflows/ci-cd.yml, .github/workflows/test.prod.yml
=> [BE] chore: 운영 환경 CI/CD workflow 파일 수정

.github/workflows/ci-cd-prod.yml, .github/workflows/ci-cd.yml
#164 
CI/CD 파이프라인 로직을 수정한다.
- 서브모듈 최신화 코드의 위치를 변경함
=> [BE] refactor: submodule 최신화 코드 위치 수정

.github/workflows/ci-cd-prod.yml, .github/workflows/ci-cd.yml
#164 
deploy 에서도 submodule을 최신화한다.
=> [BE] CI/CD 파이프라인 코드 수정

.github/workflows/ci-cd-prod.yml, .github/workflows/ci-cd.yml
#164 
workflow 시작 기준을 pull_request -> push로 변경
=> [BE] 운영 환경 CI/CD 스크립트 수정

frontend/src/apis/userFeedback.api.ts, frontend/src/components/@commons/Input/Input.tsx, frontend/src/components/@commons/TextArea/TextArea.tsx, frontend/src/components/BasicInput/BasicInput.tsx, frontend/src/components/BasicTextArea/BasicTextArea.tsx, frontend/src/components/BasicToggleButton/BasicToggleButton.style.ts, frontend/src/components/BasicToggleButton/BasicToggleButton.tsx, frontend/src/domains/user/suggestions/Suggestions.tsx, frontend/src/domains/user/suggestions/components/SecretPostOption/SecretPostOption.style.ts, frontend/src/domains/user/suggestions/components/SecretPostOption/SecretPostOption.tsx, frontend/src/domains/user/suggestions/components/UploadBox/UploadBox.style.ts, frontend/src/domains/user/suggestions/components/UploadBox/UploadBox.tsx, frontend/src/domains/user/suggestions/hooks/useSuggestionForm.ts
#150 
- api 스웨거 연결
- 컴포넌트 props 부모 컴포넌트로 변경 (api 데이터를 전송해야해서!)
- swagger에 데이터 들어오는 것 까지 확인했습니다~
=> [FE] feat: 폼 제출 api 연결 

backend/src/main/java/feedzupzup/backend/global/config/CorsConfig.java
=> [BE] fix: cors 허용 메서드에 PATCH 추가

frontend/src/domains/admin/home/AdminHome.tsx, frontend/src/domains/admin/home/hooks/useGetFeedback.ts, frontend/src/domains/user/home/UserHome.tsx, frontend/src/domains/user/suggestions/Suggestions.tsx, frontend/src/hooks/useInfinityScroll.ts
close #186 
- 피드백 리스트 2번 요청하는 에러 해결
- useEffect 구문을 제거하니 해결되었습니다!
- 캉골의 요청으로 건의하기 페이지에서 취소하기 버튼을 누르면 "/"로 이동하도록 수정했습니다!
- useInfinityScroll에 남아있는 env 내용 제거했습니다!
=> [FE] fix: 피드백 리스트 2번 요청하는 에러 해결하기

frontend/src/domains/admin/home/AdminHome.tsx, frontend/src/domains/admin/home/components/AdminFeedbackBox.tsx, frontend/src/domains/components/FeedbackBoxList/FeedbackBoxList.stories.tsx, frontend/src/types/feedback.types.ts
close #188 
관리자 페이지에서 이미지 안보이는 거 수정 
- imgUrl -> imageUrl로 변경했습니다
=> [FE] fix: 관리자 페이지에서 이미지 안보이는 거 수정 

backend/src/main/java/feedzupzup/backend/feedback/application/AdminFeedbackService.java, backend/src/main/java/feedzupzup/backend/feedback/application/FeedbackLikeService.java, backend/src/main/java/feedzupzup/backend/feedback/dto/response/AdminFeedbackListResponse.java, backend/src/test/java/feedzupzup/backend/feedback/application/FeedbackLikeServiceTest.java, backend/src/test/java/feedzupzup/backend/feedback/controller/AdminFeedbackControllerE2ETest.java, backend/src/test/java/feedzupzup/backend/feedback/controller/FeedbackLikeControllerE2ETest.java
=> [BE] refactor: Admin 피드백 조회 시 좋아요 카운트 포함되도록 수정

backend/src/main/java/feedzupzup/backend/global/config/CorsConfig.java
=> [BE] release: v1.0.2

backend/src/main/java/feedzupzup/backend/global/config/CorsConfig.java
cors origin 주소 수정
orgin 주소 *로 수정
=> [BE] hotfix: cors origin 주소 수정

backend/src/main/java/feedzupzup/backend/global/config/CorsConfig.java
=> [BE] chore: cors origin url 추가

frontend/src/components/BasicButton/BasicButton.styles.ts
close #243 
- BasicButton 스타일 변경
=> [FE] style: BasicButton 스타일 변경

frontend/src/index.css
=> [FE] style: 배경색 흰색으로 변경

backend/src/main/java/feedzupzup/backend/feedback/application/UserFeedbackService.java, backend/src/main/java/feedzupzup/backend/feedback/domain/Feedback.java, backend/src/main/java/feedzupzup/backend/feedback/dto/request/CreateFeedbackRequest.java, backend/src/main/java/feedzupzup/backend/feedback/dto/response/AdminFeedbackListResponse.java, backend/src/main/java/feedzupzup/backend/feedback/dto/response/CreateFeedbackResponse.java, backend/src/main/resources/db/migration/V2__remove_image_url_from_feedback.sql, backend/src/test/java/feedzupzup/backend/feedback/application/UserFeedbackServiceTest.java, backend/src/test/java/feedzupzup/backend/feedback/controller/FeedbackControllerE2ETest.java, backend/src/test/java/feedzupzup/backend/feedback/controller/UserFeedbackControllerE2ETest.java, backend/src/test/java/feedzupzup/backend/feedback/fixture/FeedbackFixture.java, backend/src/test/java/feedzupzup/backend/feedback/fixture/FeedbackRequestFixture.java
#249 
- 피드백 작성시 image url 제거
- api 명세에 제거
- feedback table 컬럼 제거
- 피드백 조회시 image url 제거
- flyway script 작성
모두 꼼꼼히 봐주세요! ㅎㅎ
=> [BE] refactor: 피드백 API 명세 수정

frontend/jest.config.cjs, frontend/src/domains/admin/home/AdminHome.tsx, frontend/src/domains/admin/home/hooks/useFeedbackManagement.test.ts, frontend/src/domains/hooks/useAdminModal.test.ts, frontend/src/hooks/useAdminAuth.ts, frontend/src/hooks/useModal.test.ts, frontend/tsconfig.json
#204 
- useAdminModal
- useModal
- useFeedbackManagementProps
에 대한 테스트 코드 작성 및 세팅
=> [FE] test: customhook 일부 RTL 달기

frontend/src/domains/user/OnBoarding/OnBoarding.tsx, frontend/src/hooks/useInfinityScroll.ts
close #284 
useRef 변수를 하나 만들어서, 실패할 때마다 1씩 증가시키고 해당 값이 3이되면 hasNext를 false로 설정하여 재요청을 막았습니다!
=> [FE] fix: 무한스크롤 에러시 무한 요청되는거 수정

frontend/src/domains/admin/adminDashboard/components/AdminFeedbackBox/AdminFeedbackBox.tsx, frontend/src/domains/components/FeedbackBoxHeader/FeedbackBoxHeader.tsx, frontend/src/domains/hooks/useAvatarSelector.ts, frontend/src/domains/hooks/useRandomAvata.ts, frontend/src/domains/user/userDashboard/components/UserFeedbackBox/UserFeedbackBox.tsx
#270 
-  feedbackID랑 아바타 연결
- 커스텀 훅 로직 변경
=> [FE] feat: feedbackID랑 아바타 연결

frontend/src/domains/components/FeedbackBoxFooter/FeedbackBoxFooter.tsx, frontend/src/utils/formatRelativeTime.ts
=> [FE] fix: 시간 2분전 고정 수정

frontend/src/domains/components/DashboardOverview/DashboardOverview.style.ts, frontend/src/domains/components/DashboardOverview/DashboardOverview.tsx, frontend/src/domains/components/FeedbackBoxBackGround/FeedbackBoxBackGround.tsx, frontend/src/domains/user/userDashboard/UserDashboard.tsx, frontend/src/domains/user/userDashboard/components/UserFeedbackBox/UserFeedbackBox.tsx, frontend/src/domains/user/userDashboard/hooks/useHighLighted.ts
=> [FE] fix: 모바일 환경에서 스크롤 안했을 때 게시글 보이지 않는 거 수정

frontend/src/domains/components/DashboardOverview/DashboardOverview.tsx
#315 
- % 글자 붙이기
- 완료된 상태 하드코딩된거 데이터 개수로 변경
=> [FE] fix: dashboard pannel 하드코딩 제거

frontend/src/domains/components/CheerButton/CheerButton.style.ts, frontend/src/domains/components/CheerButton/CheerButton.tsx, frontend/src/domains/components/DashboardOverview/DashboardOverview.tsx, frontend/src/domains/components/DashboardPanel/DashboardPanel.style.ts, frontend/src/domains/components/DashboardPanel/DashboardPanel.tsx, frontend/src/domains/components/LikeButton/LikeButton.style.ts, frontend/src/domains/user/FeedbackPage/FeedbackPage.tsx, frontend/src/domains/user/OnBoarding/OnBoarding.styles.ts, frontend/src/domains/user/OnBoarding/OnBoarding.tsx
close #322 
- `font-family: monospace`
- 숫자나 코드가 정렬되게 보여야 할 때
- 버튼/텍스트 안의 숫자 길이에 따라 레이아웃이 변하는 문제를 막고 싶을 때
- 타이머, 카운터, 금액 표시 등에 안정적으로 사용 가능
- 위와 같은 경우에 사용한다고 그러는데 저희 상황에 맞는 거 같아서 적용했습니다!
- `requestAnimationFrame`
- 응원하기 버튼 눌렀을 때 처음 한번만 애니메이션이 적용되는 문제를 해결하기 위해서 requestAnimationFrame을 사용했습니다.
- 기존에 animate 변수가 false에서 true로 바뀔 때 1번만 실행되었는데 매 클릭마다 애니메이션이 적용되려면 false -> true -> false -> true로 바뀌어야 했습니다.
- 그래서 매 클릭때 setAnimate(false)로 상태를 false로 바꿔주고 requestAnimationFrame을 통해 repaint 단계에서 animate상태를 true로 바꿔서 매 클릭마다 애니메이션이 적용되도록 하였습니다!
=> [FE] chore: UI/UX 개선 및 기능 수정

frontend/src/components/icons/RightArrowIcon.tsx, frontend/src/domains/admin/adminDashboard/AdminDashboard.tsx, frontend/src/domains/components/DashboardOverview/DashboardOverview.tsx, frontend/src/domains/components/DashboardOverview/DashboardOverview.utils.ts, frontend/src/domains/components/DashboardPanel/DashboardPanel.style.ts, frontend/src/domains/components/DashboardPanel/DashboardPanel.tsx, frontend/src/domains/hooks/useUserOrganizationsStatistics.ts, frontend/src/domains/user/userDashboard/UserDashboard.tsx, frontend/src/domains/user/userDashboard/hooks/useFeedbackFilter.ts, frontend/src/types/feedback.types.ts
close #329 
- 패널 클릭 효과
- 화살표 추가
https://github.com/user-attachments/assets/b557f462-49e2-4b7d-aef5-b7310dd19671
UserDashboard에 상태를 둔 이유는 추후에 해당 카테고리로 필터된 데이터를 가져와야해서 UserDashboard에 상태를 두었습니다!
=> [FE] feat: 패널 클릭 효과

backend/build.gradle
#342 
스프링부트 매트릭 수집을 위해 의존성을 추가했습니다.
설정파일도 수정했습니다!
[설정 파일 변경사항](https://github.com/feed-zup-zup/backend-submodule/commit/b6b506a5e23891979d180e017bc480e7b14d38cc)
=> [BE] feat: spring boot 매트릭 수집 위한 의존성 추가

frontend/src/apis/apiClient.ts, frontend/src/index.tsx, frontend/src/utils/errorLogger.ts
#339 
아래내용을 더 상세하게 보려면 이 [링크](https://wonderful-taker-be7.notion.site/246f333ebf828016bfc8cf5076c54d0d?source=copy_link)로 들어오시면 됩니다.
- Sentry 초기화 로직 추가 (재현 힌트 제공)
- 에러 분류 시스템 만들기
- Sentry 대시보드 설정(알림 규칙, Discord 통합)
- 개발 환경 에러는 sentry에서 추적하지 않아서 console.log 로직 추가해두었습니다.
- 코드자체에 추가된 부분은 많이는 없고, 각부분에 대한 설명(에러분류시스템 등등)이나 실제 사용법은 여기에 적어두었으니 같이 확인해주세용!
https://wonderful-taker-be7.notion.site/246f333ebf828016bfc8cf5076c54d0d?source=copy_link
=> [FE] test: Sentry 에러 모니터링 및 알림 시스템 고도화

frontend/public/index.html, frontend/src/index.css
close #338 
폰트 프리로딩
- preconnect 
- 빠른 요청
- 기존 요청보다 빠르게 요청
- preload 
-  폰트를 미리 다운로드함
- 너무 많이 사용하면 초기 렌더링 속도에 영향미침
- font-display: swap 
-  글자가 안 숨겨짐
- 기존에 글자가 안보이다가 보이는 문제 해결
- 해당 속성을 적용하면 브라우저 기본 폰트로 렌더링 후 -> 폰트 다운후 해당 폰트로 변경
배민 폰트가 중요하다고 생각하여 preload를 진행했고, preconnect는 나머지 폰트에 적용했습니다!
=> [FE] chore: 폰트 프리로딩

backend/src/main/java/feedzupzup/backend/global/log/HttpLoggingFilter.java
#373 
매트릭 수집 로그 exclude uri 추가
=> [BE] refactor: 매트릭 수집 로그 exclude uri 추가

backend/src/main/java/feedzupzup/backend/feedback/api/AdminFeedbackApi.java, backend/src/main/java/feedzupzup/backend/feedback/application/AdminFeedbackService.java, backend/src/main/java/feedzupzup/backend/feedback/controller/AdminFeedbackController.java, backend/src/main/java/feedzupzup/backend/feedback/domain/Comment.java, backend/src/main/java/feedzupzup/backend/feedback/domain/Feedback.java, backend/src/main/java/feedzupzup/backend/feedback/dto/request/UpdateFeedbackCommentRequest.java, backend/src/main/java/feedzupzup/backend/feedback/dto/response/UpdateFeedbackCommentResponse.java, backend/src/main/resources/db/migration/V9__add_column_comment_to_feedback.sql, backend/src/test/java/feedzupzup/backend/feedback/application/AdminFeedbackServiceTest.java, backend/src/test/java/feedzupzup/backend/feedback/controller/AdminFeedbackControllerE2ETest.java
#363 
- 관리자 답글 기능 추가 구현
- feedback Entity에 comment 컬럼 추가
- 그로 인한 flyway script 추가
=> [BE] feat: 관리자 답글 추가 기능 구현

backend/src/main/java/feedzupzup/backend/global/config/CorsConfig.java
개발 Swagger 주소를 http로 리다이렉트하여 처리하다 보니, http 포함한 origin 주소를 추가하였습니다.
=> [BE] feat: cors origin 주소 추가

frontend/src/analytics/types.ts, frontend/src/apis/userFeedback.api.ts, frontend/src/domains/Home.tsx, frontend/src/domains/hooks/useCategoryManager.ts, frontend/src/domains/user/FeedbackPage/FeedbackPage.tsx, frontend/src/domains/user/FeedbackPage/hooks/useFeedbackSubmit.ts, frontend/src/domains/user/OnBoarding/OnBoarding.tsx
close #375 
피드백 작성시 카테고리도 추가하여 보내기
=> [FE] fix: 피드백 작성시 카테고리도 추가하여 보내기

frontend/src/domains/hooks/useFeedbackFilterSort.ts, frontend/src/domains/user/userDashboard/UserDashboard.tsx, frontend/src/domains/user/userDashboard/components/UserFeedbackBox/UserFeedbackBox.tsx
#404 
- 나의 글 중복 호출 문제 해결
- 본인이 작성한 비밀글에 관리자 댓글이 달렸을 때, 확인을 못하는 문제 해결
- 나의 글에 초록색 border 제거
=> [FE] fix: 나의 글 중복 호출 문제 해결

backend/src/main/java/feedzupzup/backend/feedback/application/UserFeedbackService.java, backend/src/main/java/feedzupzup/backend/feedback/domain/Feedback.java, backend/src/main/java/feedzupzup/backend/feedback/domain/FeedbackRepository.java, backend/src/main/java/feedzupzup/backend/feedback/dto/request/CreateFeedbackRequest.java, backend/src/test/java/feedzupzup/backend/feedback/application/AdminFeedbackServiceTest.java, backend/src/test/java/feedzupzup/backend/feedback/application/FeedbackLikeCounterTest.java, backend/src/test/java/feedzupzup/backend/feedback/application/FeedbackLikeServiceTest.java, backend/src/test/java/feedzupzup/backend/feedback/application/FeedbackStatisticServiceTest.java, backend/src/test/java/feedzupzup/backend/feedback/application/UserFeedbackServiceTest.java, backend/src/test/java/feedzupzup/backend/feedback/controller/AdminFeedbackControllerE2ETest.java, backend/src/test/java/feedzupzup/backend/feedback/controller/FeedbackLikeControllerE2ETest.java, backend/src/test/java/feedzupzup/backend/feedback/controller/UserFeedbackControllerE2ETest.java, backend/src/test/java/feedzupzup/backend/feedback/fixture/FeedbackFixture.java
#418 
Feedback에 있는 Organization 객체를 간접참조에서 직접참조로 수정한다
커밋 나누기 실패했습니다. 하나의 흐름이 자연스러운듯. 메인 로직 변경된거 위주로 확인해주세요
=> [BE] refactor: 간접참조 -> 직접참조로 전면 리팩토링

frontend/src/hooks/useLayoutConfig.ts
#420 
- 기본 라우터 (/)이동시 헤더 관련 오류가 났던 부분 수정했습니다!
=> [FE] fix: 바텀네비게이션, 헤더관련 에러 수정

backend/src/main/java/feedzupzup/backend/global/config/CorsConfig.java
=> [BE] refactor: cors 추가

backend/src/main/java/feedzupzup/backend/admin/domain/Admin.java, backend/src/main/java/feedzupzup/backend/admin/domain/AdminRepository.java, backend/src/main/java/feedzupzup/backend/admin/domain/vo/AdminName.java, backend/src/main/java/feedzupzup/backend/admin/domain/vo/EncodedPassword.java, backend/src/main/java/feedzupzup/backend/admin/domain/vo/LoginId.java, backend/src/main/java/feedzupzup/backend/admin/domain/vo/Password.java, backend/src/main/java/feedzupzup/backend/auth/application/AuthService.java, backend/src/main/java/feedzupzup/backend/auth/application/PasswordEncoder.java, backend/src/main/java/feedzupzup/backend/auth/dto/request/SignUpRequest.java, backend/src/main/java/feedzupzup/backend/auth/dto/response/LoginResponse.java, backend/src/main/java/feedzupzup/backend/auth/dto/response/SignUpResponse.java, backend/src/main/java/feedzupzup/backend/auth/infrastructure/BCryptPasswordEncoderAdapter.java, backend/src/test/java/feedzupzup/backend/admin/domain/vo/PasswordTest.java, backend/src/test/java/feedzupzup/backend/auth/application/AuthServiceTest.java, backend/src/test/java/feedzupzup/backend/auth/controller/AuthControllerE2ETest.java
Password 객체 헷갈려, EncodedPassword 객체 생성하여 리팩토링했습니다~!
=> [BE] refactor: EncodedPassword 객체 생성

frontend/src/domains/admin/Settings/Settings.tsx
#401 
- 빌드 테스트입니다.
- 주석만 추가한뒤 머지해보겠습니다!
=> [FE] setting : 개발서버, 프로덕션 서버 CD 세팅

frontend/src/components/icons/ArrowRightIcon.tsx, frontend/src/components/icons/PlusIcon.tsx, frontend/src/domains/admin/AdminHome/AdminHome.style.ts, frontend/src/domains/admin/AdminHome/AdminHome.tsx, frontend/src/domains/admin/AdminHome/components/AdminHomeHeader/AdminHomeHeader.stories.tsx, frontend/src/domains/admin/AdminHome/components/AdminHomeHeader/AdminHomeHeader.style.ts, frontend/src/domains/admin/AdminHome/components/AdminHomeHeader/AdminHomeHeader.tsx, frontend/src/domains/admin/AdminHome/components/FeedbackRoom/FeedbackRoom.stories.tsx, frontend/src/domains/admin/AdminHome/components/FeedbackRoom/FeedbackRoom.style.ts, frontend/src/domains/admin/AdminHome/components/FeedbackRoom/FeedbackRoom.tsx, frontend/src/domains/admin/AdminHome/components/FeedbackRoomList/FeedbackRoomList.style.ts, frontend/src/domains/admin/AdminHome/components/FeedbackRoomList/FeedbackRoomList.tsx, frontend/src/domains/admin/AdminHome/components/StatusBar/StatusBar.stories.tsx, frontend/src/domains/admin/AdminHome/components/StatusBar/StatusBar.style.ts, frontend/src/domains/admin/AdminHome/components/StatusBar/StatusBar.tsx, frontend/src/domains/admin/AdminHome/mocks/feedbackRooms.ts
#460
- 프로그래스바 제작
- 피드백 방 컴포넌트 제작
=> [FE] feat: 관리자 메인화면 UI 

backend/src/main/resources/db/migration/V16__create_notification_token_table.sql
=> [BE] refactor: Notification DDL 작성

frontend/public/index.html, frontend/src/components/Modal/Modal.tsx, frontend/src/constants/routes.ts, frontend/src/domains/Home.tsx, frontend/src/domains/admin/AdminHome/components/FeedbackRoomList/FeedbackRoomList.tsx, frontend/src/domains/admin/AdminHome/mocks/feedbackRooms.ts, frontend/src/domains/user/FeedbackPage/FeedbackPage.tsx, frontend/src/domains/user/OnBoarding/OnBoarding.tsx, frontend/src/router.tsx, frontend/src/utils/protectedRoute.tsx
#477
- 라우터 경로 변경
- protectedRouter 설정 
- login api 수정하면서 권한 연결할 예정
- Modal 컴포넌트에서  `if (!isOpen) return null;` 이거 없으니까 카테코리 누르자마자 바로 제출되더라구요 
- https://dev.feedzupzup.com/ 여기서 확인해보심 됩니다
- 해당 버그 수정하기 위해서 위에 속성 추가해뒀어요!
=> [FE] feat: router 설정 

backend/src/main/resources/db/migration/V18__add_uuid_column_to_organization.sql
#493 
organization DDL을 추가합니다.
=> [BE] organization DDL 추가

backend/src/test/java/feedzupzup/backend/qr/domain/SiteUrlTest.java
#417 
qr 환경별 baseurl 변수 변경에 따른 테스트 수정
=> [BE] chore: qr 환경별 baseurl 변수 변경

backend/src/main/java/feedzupzup/backend/auth/presentation/api/AdminAuthApi.java, backend/src/main/java/feedzupzup/backend/auth/presentation/controller/AdminAuthController.java, backend/src/main/java/feedzupzup/backend/auth/presentation/interceptor/AdminCheckInterceptor.java, backend/src/main/java/feedzupzup/backend/auth/presentation/session/HttpSessionManager.java
#526 
잘못된 세션으로 `/admin`에 접근시 인터셉터에서 쿠키 삭제하는 로직 추가
=> [BE] refactor: 잘못된 세션으로 접근 시 세션 쿠키 삭제하는 로직 추가

backend/src/main/java/feedzupzup/backend/global/response/ErrorCode.java, backend/src/main/java/feedzupzup/backend/qr/api/QRApi.java, backend/src/main/java/feedzupzup/backend/qr/controller/QRController.java, backend/src/main/java/feedzupzup/backend/qr/dto/request/QRCodeUploadRequest.java, backend/src/main/java/feedzupzup/backend/qr/dto/response/QRDownloadUrlResponse.java, backend/src/main/java/feedzupzup/backend/qr/dto/response/QRResponse.java, backend/src/main/java/feedzupzup/backend/qr/service/QRService.java, backend/src/main/java/feedzupzup/backend/s3/controller/S3Controller.java, backend/src/main/java/feedzupzup/backend/s3/controller/S3ExceptionHandler.java, backend/src/main/java/feedzupzup/backend/s3/exception/S3PresignedException.java, backend/src/main/java/feedzupzup/backend/s3/service/S3PresignedDownloadService.java, backend/src/main/java/feedzupzup/backend/s3/service/S3PresignedUploadService.java, backend/src/main/java/feedzupzup/backend/s3/service/S3UploadService.java, backend/src/test/java/feedzupzup/backend/qr/controller/QRControllerE2ETest.java, backend/src/test/java/feedzupzup/backend/qr/service/QRServiceTest.java, backend/src/test/java/feedzupzup/backend/s3/service/S3PresignedDownloadServiceTest.java, backend/src/test/java/feedzupzup/backend/s3/service/S3UploadServiceTest.java
#532 
QR 이미지를 다운로드 받을 수 있는 url을 발급하는 기능을 추가했습니다.
QR Image url 조회 기능이랑 플로우가 비슷해서 빠르게 보실 수 있을거에요~~
=> [BE] QR 이미지 다운로드 url 발급 기능 추가

.github/workflows/be-deploy-prod.yml
#517 
prod 환경 스프링 부트 이미지 태그를 Git commit 해시로 변경
=> [BE] chore: prod deploy 스크립트 수정

backend/src/main/java/feedzupzup/backend/auth/presentation/interceptor/AdminCheckInterceptor.java, backend/src/main/java/feedzupzup/backend/auth/presentation/resolver/AdminSessionArgumentResolver.java, backend/src/main/java/feedzupzup/backend/auth/presentation/session/HttpSessionManager.java, backend/src/test/java/feedzupzup/backend/auth/presentation/interceptor/AdminCheckInterceptorTest.java
#530 
세션을 찾을 수 없을 시 세션을 삭제하는 로직을 추가합니다.
=> [BE] fix: 세션을 찾을 수 없을 시 삭제 로직 추가

backend/src/main/java/feedzupzup/backend/auth/presentation/session/HttpSessionManager.java
=> [BE] 로그아웃시 세션 쿠키 삭제 되도록 수정

backend/src/main/java/feedzupzup/backend/auth/presentation/session/HttpSessionManager.java
=> [BE] 로그아웃시 세션 쿠키 삭제

backend/src/main/java/feedzupzup/backend/global/config/WebConfig.java
=> [BE] 개발 서버 cors 설정 수정

backend/src/main/java/feedzupzup/backend/global/config/WebConfig.java
=> [BE] cors 설정 수정

.github/workflows/release.yml
=> [FE] fix: 릴리즈 조건 변경 

backend/src/main/java/feedzupzup/backend/global/config/WebConfig.java
=> [BE] fix: cors 헤더 수동 설정

backend/src/main/java/feedzupzup/backend/auth/presentation/filter/CorsFilter.java, backend/src/main/java/feedzupzup/backend/global/config/WebConfig.java
=> [BE] fix: cors Filter를 생성

backend/src/main/java/feedzupzup/backend/feedback/api/AdminFeedbackApi.java, backend/src/main/java/feedzupzup/backend/feedback/application/AdminFeedbackService.java, backend/src/main/java/feedzupzup/backend/feedback/controller/AdminFeedbackController.java, backend/src/main/java/feedzupzup/backend/feedback/domain/FeedbackRepository.java, backend/src/main/java/feedzupzup/backend/feedback/dto/response/FeedbackStatisticResponse.java, backend/src/test/java/feedzupzup/backend/feedback/application/AdminFeedbackServiceTest.java, backend/src/test/java/feedzupzup/backend/feedback/controller/AdminFeedbackControllerE2ETest.java
#561 
관리자가 피드백 전체 처리 현황을 조회할 수 있는 API를 구현합니다.
=> [BE] feat: 피드백 전체 처리 현황 조회 API 구현

frontend/src/components/BasicButton/BasicButton.stories.tsx, frontend/src/components/BasicButton/BasicButton.styles.ts, frontend/src/components/BasicButton/BasicButton.tsx, frontend/src/domains/admin/components/QRModal/QRModal.tsx, frontend/src/domains/admin/components/QRModal/components/QRImageSection/QRImageSection.tsx, frontend/src/domains/admin/components/QRModal/components/QRUrlSection/QRUrlSection.tsx
close #445 
BasicButton props에서 number | string로 되어 있던 타입들을 string으로 통일했습니다!
=> [FE] feat: BasicButton props: string | number; -> string으로 변경 

frontend/src/domains/user/userDashboard/UserDashboard.tsx
서비스 라우터 관련 에러 수정 
1. url의 형태가 접속할수없는형태임 -> 이건 서버에서 url을 변경해서 보내주는 걸로 했습니다!
2. 글쓰러가기 누르면 /으로 이동함 -> uuid/submit 형태로 이동
=> [FE] fix: 서비스 라우터 관련 에러 수정 

.github/workflows/release.yml
release.yml 주석 수정 및 릴리즈 브랜치 이름 주석 추가
=> [FE] test: 시맨틱 릴리즈 버저닝 테스트2 

.github/workflows/release.yml
=> [FE] test: 시맨틱 릴리즈 버저닝 테스트 

.github/workflows/release.yml
=> [FE] test: 시맨틱 릴리즈 버저닝 테스트

backend/src/main/java/feedzupzup/backend/global/log/RequestLogMessage.java, backend/src/main/java/feedzupzup/backend/qr/domain/SiteUrl.java, backend/src/main/java/feedzupzup/backend/qr/service/QRService.java, backend/src/test/java/feedzupzup/backend/qr/controller/QRControllerE2ETest.java, backend/src/test/java/feedzupzup/backend/qr/service/QRServiceTest.java
=> [BE] refactor: 사용자 QR 접속 페이지 url 변경

.github/workflows/release.yml
=> [FE] test: 시맨틱 릴리즈 버저닝 테스트 (minor)

frontend/src/domains/components/DashboardOverview/DashboardOverview.style.ts
#634 
사용자의 입력에 따라 보여지는 글씨는 pretendard로 변경했습니다! (지금은 이것만 수정함)
=> [FE] fix: 킼킼킼 등 정상적이지 않은 텍스트에 대해서 BMHANNAPro로 인식이 안되는오류

frontend/src/domains/admin/Settings/hooks/useFCMManager.ts, frontend/src/services/notificationService.ts, frontend/src/utils/notificationUtils.ts
#609 
- 윌슨이랑 개발중인데 개발서버에서 디버깅을 해봐야할것가아서 콘솔 내용 추가하고 PR올립니당!
=> chore: 로깅을 위한 콘솔 메세지 추가

backend/src/main/java/feedzupzup/backend/notification/infrastructure/FcmPushNotifier.java
=> [BE] chore: 알람 로직에 로그 추가

backend/src/main/java/feedzupzup/backend/notification/event/NotificationEventListener.java
=> [BE] refactor: origanizer에서 adminId가져오는걸로 수정

frontend/src/domains/admin/AdminHome/hooks/useAdminStatistics.ts, frontend/src/hooks/useApiErrorHandler.ts, frontend/src/hooks/useCursorInfiniteScroll.ts
#653 
권한 없는 uuid로 접근했을 때 접근 제한
=> [FE] fix: 권한 없는 uuid로 접근했을 때 접근 제한

backend/src/main/java/feedzupzup/backend/notification/application/NotificationService.java
=> [BE] Fcm 저장 로직 수정

frontend/src/apis/apiClient.ts, frontend/src/domains/admin/Settings/hooks/useFCMManager.ts, frontend/src/domains/admin/Settings/hooks/useNotificationSettingMutation.ts, frontend/src/services/notificationService.ts, frontend/src/utils/notificationUtils.ts
#663 
- 위의 작업과
- 릴리즈 이후 apiClinet의 없어진 코드를 롤백시켰습니다.
=> [FE] chore: 알람 설정시 로깅 제거 및 강제 리다이렉트 제거

.github/workflows/be-test.yml, backend/src/main/resources/db/migration/V24__refactor_notification_token_to_notification.sql
=> [BE] hotfix: release 1.2.3

backend/src/main/resources/db/migration/V24__refactor_notification_token_to_notification.sql
=> [BE] hotfix: release v1.2.7

frontend/src/domains/admin/EditRoomModal/hooks/useDeleteOrganization.ts
방 삭제시 바로 반영안되는 문제 해결
https://github.com/user-attachments/assets/ab6f9969-d96a-4e8b-b49a-b0ea3216b065
=> [FE] fix: 방 삭제시 바로 반영안되는 문제 해결

frontend/src/components/Header/Header.style.ts, frontend/src/components/Header/Header.tsx, frontend/src/components/Header/HeaderMoreIcon/HeaderMoreIcon.styles.ts, frontend/src/components/Header/HeaderMoreIcon/HeaderMoreIcon.tsx, frontend/src/components/Header/MoreMenu/MoreMenu.styles.ts, frontend/src/components/Header/MoreMenuItem/MoreMenuItem.styles.ts, frontend/src/components/Header/MoreMenuItem/MoreMenuItem.tsx, frontend/src/components/icons/ShareIcon.tsx, frontend/src/components/icons/SmallSettingIcon.tsx, frontend/src/components/icons/TrashCanIcon.tsx
#766 
- 관리자 더보기 버튼 호버 스타일 추가
- 더보기 모달 폰트 크기, 모달 크기 증가
- 관리자 헤더 뒤로가기 호버 스타일 추가
개선 후
https://github.com/user-attachments/assets/80e7c19b-be4e-4ca2-b199-af1c8f176a6e
=> [FE] refactor: 관리자 더보기 버튼 ux개선 

frontend/src/components/Modal/Modal.styles.ts, frontend/src/components/Tag/Tag.styles.ts, frontend/src/components/Tag/Tag.tsx, frontend/src/domains/admin/CreateRoomModal/CreateRoomModal.tsx, frontend/src/domains/admin/EditRoomModal/EditRoomModal.tsx, frontend/src/domains/admin/components/QRModal/QRModal.tsx, frontend/src/domains/admin/components/RoomCategoryItem/RoomCategoryItem.styles.ts, frontend/src/domains/admin/components/RoomCategoryList/RoomCategoryList.styles.ts, frontend/src/domains/admin/components/RoomCategoryTag/RoomCategoryTag.tsx
#777 
- 방수정, 방삭제 모달 너비 증가
- 방수정, 방삭제 카테고리 패딩 늘려서 선택하기 쉽게 ux 개선
- 선택된 카테고리 제거할 때 X 버튼 누리기 힘들어서 그냥 클릭만 하면 제거 되도록 ux 개선
- 전에는 카테고리 리스트 높이가 너무 좁았는데 카테고리 리스트 높이 증가
- QRmodal 도 통일성을 위해서 너비 동일하게 변경
개선 전
개선 후
https://github.com/user-attachments/assets/298099a0-8a94-4a06-aa18-8c213f1a5504
=> [FE] refactor: 방 수정, 방 생성 모달 크기 증가

.github/workflows/front-ci.yml
#787 
성능자동화 시트가 merge시에 PR링크가 안담기는 문제가 있어서 CI를 수정했습니다.
merge시에 어떤지 테스트 하지 못하기때문에 해당 PR로 테스트 해보겠습니다! 문
=> [FE] chore: 성능 자동화 시트 merge시 PR링크 안담기는 문제
